# Generated by Django 4.0.6 on 2022-08-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortcode',
            field=models.CharField(default='urlcurta', max_length=15),
            preserve_default=False,
        ),
    ]
