# Generated by Django 4.0.6 on 2022-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encurtador', '0002_url_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
